repos:
  - repo: local
    hooks:
      - id: checkov
        name: checkov
        entry: checkov
        language: system
        pass_filenames: false
        always_run: true
        args: [-d, ., --compact]